### ISSUE TITLE
How can I get mean and covariance of built GMM from samples?

### ISSUE THREAD

**Issue by iamlvm** [andreacasalino/Gaussian-Mixture-Model#4]

**Comment by andreacasalino** [comment]
Dear John, 

thank you for the interest in this library. 
You can build the GMM from samples using for example expectation maximization:
  gauss::gmm::GaussianMixtureModel learnt_model(
      gauss::gmm::ExpectationMaximization(samples, number_of_expected_clusters)
  );

Then, you can always access the set of clusters composing the GMM calling GaussianMixtureModel::getClusters().
Each element in the returned vector is a gauss::gmm::Cluster structure, containing the weight as well as the Gaussian distribution associated to a particular cluster.
You can access the mean or covariance of such a distribution by calling GaussianDistribution::getMean() and GaussianDistribution::getCovariance().
